servers:
  web:
    hosts:
      - 206.189.157.255

proxy:
  ssl: true
  host: hq.ksuntech.com

env:
  clear:
    DB_HOST: postgres-db
    DB_NAME: ecom_admin_app_production
    DB_USERNAME: ecom_admin_app
    APP_HOST: https://hq.ksuntech.com

accessories:
  db:
    service: postgres
    image: postgres:18
    host: 206.189.157.255
    env:
      clear:
        POSTGRES_DB: ecom_admin_app_production
        POSTGRES_USER: ecom_admin_app
      secret:
        - POSTGRES_PASSWORD
    directories:
      - /var/data/postgres:/var/lib/postgresql
    options:
      network: kamal
